### ISSUE TITLE
Bug: openjd check does not handle duplicate keys 

### ISSUE THREAD

**Issue by AWS-Samuel** [OpenJobDescription/openjd-cli#125]
### Describe the bug

Given a job template, which has duplicate keys. `openjd check` will consider the job template as valid, even though it's not valid yaml. 

### Expected Behaviour

The template will not be considered valid, due to having duplicate keys

### Current Behaviour

The template will be considered valid, even with duplicate keys.

### Reproduction Steps

Given the template:

```yaml
specificationVersion: 'jobtemplate-2023-09'
specificationVersion: 'jobtemplate-2023-09'
name: Foo
name: Foo
steps:
- name: Bar
  script:
    actions:
      onRun:
        command: Baz
        command: Baz
      onRun:
        command: Baz
        command: Baz
    actions:
      onRun:
        command: Baz
        command: Baz
      onRun:
        command: Baz
        command: Baz
```

```
> openjd check template.yaml
Template at 'template.yaml' passes validation checks.
```
