### ISSUE TITLE
Bug: `run` is not correctly exiting environments when there is a task failure

### ISSUE THREAD

**Issue by ddneilson** [OpenJobDescription/openjd-cli#74]
### Expected Behaviour

The CLI is not running Environment Exits when a task failure is encountered; this is incorrect. When a Task fails, all Environments that have been Entered must also be Exited. See the state machine in: https://github.com/OpenJobDescription/openjd-specifications/wiki/How-Jobs-Are-Run#sessions

The expectation is that in the example provided in this ticket, the session ends with running the `onExit` command of the environment. It does not do that.

### Current Behaviour

```
...
Wed Apr  3 14:39:38 2024        ==============================================
Wed Apr  3 14:39:38 2024        --------- Running Task
Wed Apr  3 14:39:38 2024        ==============================================
Wed Apr  3 14:39:38 2024        ----------------------------------------------
Wed Apr  3 14:39:38 2024        Phase: Setup
Wed Apr  3 14:39:38 2024        ----------------------------------------------
Wed Apr  3 14:39:38 2024        ----------------------------------------------
Wed Apr  3 14:39:38 2024        Phase: Running action
Wed Apr  3 14:39:38 2024        ----------------------------------------------
Wed Apr  3 14:39:38 2024        Running command /tmp/OpenJD/sample_session6y58u_th/tmpj7x9cj8i.sh
Wed Apr  3 14:39:38 2024        Command started as pid: 23413
Wed Apr  3 14:39:38 2024        Output:
Wed Apr  3 14:39:38 2024        Open Job Description CLI: ERROR executing action: 'Run Step 'Test' with Task parameters '{}'' (see Task logs for details)
Wed Apr  3 14:39:38 2024        Open Job Description CLI: Local Session ended! Now cleaning up Session resources.

--- Results of local session ---

Session ended with errors; see Task logs for details
```

### Reproduction Steps

```bash
openjd run testcase.yaml --step Test
```

### Code Snippet

```yaml
name: IncorrectLogic
specificationVersion: jobtemplate-2023-09
steps:
- name: Test
  stepEnvironments:
  - name: Bracket
    script:
      actions:
        onEnter:
          command: bash
          args: [ "-c", "echo Entering" ]
        onExit:
          command: bash
          args: [ "-c", "echo Exiting" ]
  script:
    actions:
      onRun:
        command: bash
        args: ["-c", "exit 1"]
```
