### ISSUE TITLE
Bug: Does not exit if an action reaches its timeout

### ISSUE THREAD

**Issue by ddneilson** [OpenJobDescription/openjd-cli#96]
### Expected Behaviour

The CLI should exit with a non-zero exit code when the task has been ended via timeout.

### Current Behaviour

If you run a Task that has a timeout, and that timeout is reached then the Task is properly terminated but the CLI itself fails to exit. It appears to be frozen waiting on some sort of internal state signal that never comes.

### Reproduction Steps

Given the template:

```yaml
specificationVersion: jobtemplate-2023-09
name: TimeoutTest
steps:
  - name: Timeout
    script:
      actions:
        onRun:
          command: bash
          args:
          - "{{Task.File.Sleep}}"
          timeout: 3
      embeddedFiles:
        - name: Sleep
          type: TEXT
          runnable: true
          filename: sleep.sh
          data: |
            #!/bin/bash
            while true; do
              echo "Sleeping for 1s..."
              sleep 1
            done
```

Run it as:

```bash
% openjd run --step Timeout fail.template.yaml
Mon Jul  8 16:47:53 2024	
Mon Jul  8 16:47:53 2024	==============================================
Mon Jul  8 16:47:53 2024	--------- Running Task
Mon Jul  8 16:47:53 2024	==============================================
Mon Jul  8 16:47:53 2024	----------------------------------------------
Mon Jul  8 16:47:53 2024	Phase: Setup
Mon Jul  8 16:47:53 2024	----------------------------------------------
Mon Jul  8 16:47:53 2024	Writing embedded files for Task to disk.
Mon Jul  8 16:47:53 2024	Mapping: Task.File.Sleep -> /private/var/folders/93/p7mk60kn69ggyc87dfbwtht80000gr/T/OpenJD/sample_sessionnsemo5_7/embedded_filestfjgkf2m/sleep.sh
Mon Jul  8 16:47:53 2024	Wrote: Sleep -> /private/var/folders/93/p7mk60kn69ggyc87dfbwtht80000gr/T/OpenJD/sample_sessionnsemo5_7/embedded_filestfjgkf2m/sleep.sh
Mon Jul  8 16:47:53 2024	----------------------------------------------
Mon Jul  8 16:47:53 2024	Phase: Running action
Mon Jul  8 16:47:53 2024	----------------------------------------------
Mon Jul  8 16:47:53 2024	Running command /private/var/folders/93/p7mk60kn69ggyc87dfbwtht80000gr/T/OpenJD/sample_sessionnsemo5_7/tmp2zquiz9y.sh
Mon Jul  8 16:47:53 2024	Command started as pid: 45091
Mon Jul  8 16:47:53 2024	Output:
Mon Jul  8 16:47:53 2024	Sleeping for 1s...
Mon Jul  8 16:47:55 2024	Sleeping for 1s...
Mon Jul  8 16:47:56 2024	Sleeping for 1s...
Mon Jul  8 16:47:56 2024	TIMEOUT - Runtime limit reached at 2024-07-08T21:47:56Z. Canceling action.
Mon Jul  8 16:47:56 2024	Canceling subprocess 45091 via termination method at 2024-07-08T21:47:56Z.
Mon Jul  8 16:47:56 2024	INTERRUPT: Running: /Users/user/.venv/lib/python3.9/site-packages/openjd/sessions/_scripts/_posix/_signal_subprocess.sh 45091 kill False True
Mon Jul  8 16:47:56 2024	/private/var/folders/93/p7mk60kn69ggyc87dfbwtht80000gr/T/OpenJD/sample_sessionnsemo5_7/embedded_filestfjgkf2m/sleep.sh: line 5: 45095 Killed: 9               sleep 1
Mon Jul  8 16:47:56 2024	Sleeping for 1s...
^Z
zsh: suspended  openjd run --step Timeout fail.template.yaml
```

Environment:
* macOS Sonoma 14.5
* Apple M1 Pro
* Running via terminal

### Code Snippet

N/A
